project_id = "osqanpfiprsbcontotlq"

[functions.import-invoices]
verify_jwt = false

[functions.polar-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-upload-link]
verify_jwt = false

[functions.gmail-auth]
verify_jwt = false

[functions.gmail-webhook]
verify_jwt = false

[functions.gmail-sync]
verify_jwt = false
